import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

import Topo from "@/componentes/Topo/Topo";
import SecaoCapa from "@/componentes/SecaoCapa/SecaoCapa";
import SecaoProdutos from "@/componentes/SecaoProdutos/SecaoProdutos";
import SecaoSobre from "@/componentes/SecaoSobre/SecaoSobre";
import SecaoContato from "@/componentes/SecaoContato/SecaoContato";
import Rodape from "@/componentes/Rodape/Rodape";


export default function Home() {
  return (
    <>
      <Head>
        <title>Óticas Vida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Topo/>
      <SecaoCapa/>
      <SecaoProdutos/>
      <SecaoSobre/>
      <SecaoContato/>
      <Rodape/>
    </>
  );
}
